name: "openEuler OpenStack packages check"
description: "Check the OpenStack packages broken or not in openEuler"
author: "liusheng"
inputs:
  openstack_release:
    description: "Specify OpenStack release, support: Rocky, Queens, Victoria, Wallaby"
    required: true
  openeuler_release:
    description: "Specify openEuler release, support: 20.03, 21.03, 21.09"
    required: true
  gitee_pat:
    description: "Gitee personal access token"
    required: true
outputs:
  unmatched_projects_row:
    description: "List of projects unmatched version(row format)"
  unmatched_projects_html:
    description: "List of projects unmatched version(html format)"
  unmatched_projects_csv:
    description: "List of projects unmatched version(csv format)"
  unmatched_projects_json:
    description: "List of projects unmatched version(json format)"
  unmatched_projects_string:
    description: "List of projects unmatched version(string format)"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.openstack_release }}
    - ${{ inputs.openeuler_release }}
    - ${{ inputs.gitee_pat }}